[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.21", features = ["derive", "string"] }
dotenv = "0.15.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
seq-macro = "0.3.5"
